# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://dotenfund.github.io
title: Dark Omegan Trust and Endeavor Fund
email: dotenfund@gmail.com
banner: brand-banner.png
logo:
  transparent: dotenfund-transparent.png
  gray: dotenfund-gray.png
author: Dark Omegan
description: Trust and Endeavor Fund
copyright: 'Copyright &copy; 2018 Dark Omegan Trust and Endeavor Fund. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email #Email
    url: dotenfund@gmail.com

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]